services:

  api:
    build:
      context: ../backend

    container_name: fastapi-api

    restart: unless-stopped

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://admin:secret@postgres:5432/damage_ai

    volumes:
      - ../backend:/app
      - ../backend/uploads:/app/uploads
      - ../models:/models

    networks:
      - damage-net

  postgres:
    image: pgvector/pgvector:pg16

    container_name: postgres-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: damage_ai

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

      # AUTO RUN INIT.SQL FROM NEW BACKEND MIGRATIONS
      - ../backend/migrations/schema.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - damage-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d damage_ai"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4

    container_name: pgadmin

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    networks:
      - damage-net

volumes:
  postgres_data:

networks:
  damage-net:
    driver: bridge
