"""
Generates a YOLO data.yaml for fine-tuning from intern correction annotations.
Run this before each fine-tune cycle.

Usage:
  python scripts/generate_corrections_yaml.py

Output:
  configs/corrections_data.yaml — ready for yolo train
  Prints train/val split counts and the training command.
"""

import random
import shutil
from pathlib import Path

YOLO_CLASSES = ["dent", "scratch", "crack", "glass_shatter", "lamp_broken", "tire_flat"]
MIN_IMAGES = 10


def main():
    img_dir = Path("data/yolo_corrections/images")
    lbl_dir = Path("data/yolo_corrections/labels")

    if not img_dir.exists() or not any(img_dir.iterdir()):
        print(f"No correction images found in {img_dir}. Collect bbox annotations first.")
        return

    images = [
        p for p in img_dir.iterdir()
        if p.suffix.lower() in (".jpg", ".jpeg", ".png")
        and (lbl_dir / (p.stem + ".txt")).exists()
    ]

    if len(images) < MIN_IMAGES:
        print(f"Only {len(images)} annotated images. Need ≥{MIN_IMAGES} for a fine-tune run.")
        return

    random.shuffle(images)
    split = int(len(images) * 0.8)
    train_imgs = images[:split]
    val_imgs = images[split:]

    train_dir = Path("data/yolo_corrections/train")
    val_dir = Path("data/yolo_corrections/val")
    for d in (
        train_dir / "images", train_dir / "labels",
        val_dir / "images", val_dir / "labels",
    ):
        d.mkdir(parents=True, exist_ok=True)

    for img in train_imgs:
        shutil.copy2(img, train_dir / "images" / img.name)
        lbl = lbl_dir / (img.stem + ".txt")
        if lbl.exists():
            shutil.copy2(lbl, train_dir / "labels" / lbl.name)

    for img in val_imgs:
        shutil.copy2(img, val_dir / "images" / img.name)
        lbl = lbl_dir / (img.stem + ".txt")
        if lbl.exists():
            shutil.copy2(lbl, val_dir / "labels" / lbl.name)

    abs_path = Path("data/yolo_corrections").resolve()
    yaml_content = f"""# Auto-generated by scripts/generate_corrections_yaml.py
# Fine-tune dataset from intern corrections
# Train: {len(train_imgs)} images | Val: {len(val_imgs)} images

path: {abs_path}
train: train/images
val: val/images

nc: {len(YOLO_CLASSES)}
names: {YOLO_CLASSES}
"""

    out = Path("configs/corrections_data.yaml")
    out.write_text(yaml_content)

    print(f"Written: {out}")
    print(f"Train: {len(train_imgs)} images")
    print(f"Val:   {len(val_imgs)} images")
    print()
    print("Run fine-tune with:")
    print(
        "  yolo train"
        " model=models/damage_detection/models/best.pt"
        " data=configs/corrections_data.yaml"
        " epochs=20 imgsz=640 batch=8 lr0=0.001 freeze=10"
        " project=models/damage_detection/fine_tuned"
        " name=correction_run"
    )


if __name__ == "__main__":
    main()
